# Generated by Django 6.0.2 on 2026-03-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
